"""Hijack fingerprints — one reviewable list of what a stolen domain looks like.

Everything that decides "this page is not the company's" lives here, in lists a
person can read and argue with, because these lists will be wrong in both
directions and somebody has to be able to fix them without reading the fetch
code.

WHAT THIS IS FOR

An expired domain gets re-registered and pointed at whatever pays. Four of the
572 companies in this pipeline had it happen: Decatur Plastic Products resolves
to an Indonesian togel site, Addman Engineering to a Russian sports-betting
page, Sip and Share Wines through two redirects to another togel page, and
Nextremity Solutions to an Azerbaijani casino. Every claim read from those pages
was correctly formed — sourced, tiered, dated — and entirely false.

THREE LESSONS FROM THE FORENSICS, ENCODED HERE

1. Word boundaries, not substrings. A first pass matching "cialis" anywhere
   flagged six honest manufacturers, because "specialist" contains it. Every
   match here is a whole word.

2. No length ceiling on parking detection. The previous check required a page
   under 4,000 characters, on the reasoning that a placeholder is small. The
   Decatur hijack is 586KB of stuffed content and sailed through.

3. Domain drift is not evidence of anything on its own. Roughly thirty of these
   companies moved domains legitimately — lci1.com to lippert.com, Nowak
   Precision to Nexos Avian, which the grant listing itself names as the DBA.
   Drift matters only when the destination content also fails coherence.

LIMITS, STATED PLAINLY

These are heuristics over text. They will miss a hijack that reads like a
manufacturer, and they will occasionally flag an honest company — a firm that
genuinely sells casino furniture trips the gambling family. That is why nothing
here deletes or discards: a fingerprint match routes a record to a human with
the matched marker recorded, and a human decides. The cost of a false positive
is one review; the cost of a false negative is an email to a prospect quoting a
gambling site back at them.
"""

from __future__ import annotations

import re
from typing import Any
from urllib.parse import urlparse

# --------------------------------------------------------------- keyword families

GAMBLING = (
    "togel", "toto", "judi", "bandar", "casino", "kasino", "poker", "sportsbook",
    "betting", "bookmaker", "taruhan", "jackpot", "maxwin", "slot gacor",
    "situs slot", "situs toto", "link alternatif", "agen togel", "rtp live",
    "bet365", "baccarat", "roulette",
)
PHARMA = (
    "viagra", "cialis", "tadalafil", "sildenafil", "kamagra",
    "no prescription", "canadian pharmacy",
)
ADULT = ("porn", "xxx", "escort", "camgirl", "webcam girls", "hookup")
PARKING = (
    "this domain is for sale", "buy this domain", "domain may be for sale",
    "the domain name", "hugedomains", "sedo.com", "dan.com", "afternic",
    "domain broker", "make an offer", "this webpage was generated by the domain owner",
    "parked free", "courtesy of godaddy",
)

FAMILIES: dict[str, tuple[str, ...]] = {
    "gambling": GAMBLING,
    "pharma": PHARMA,
    "adult": ADULT,
    "parking": PARKING,
}
"""The families, by name. Add to these rather than to the matching code."""

NON_ENGLISH_MARKERS = (
    # Indonesian/Malay function words. Both togel hijacks are Indonesian, and
    # function words survive translation-proofing better than nouns do.
    "yang", "dengan", "untuk", "adalah", "situs", "permainan", "daftar",
    "terpercaya", "resmi", "kami", "anda", "tidak", "bisa", "akan", "hari ini",
    "dan", "atau", "sangat", "lebih",
)
NON_ENGLISH_THRESHOLD = 5
"""Distinct markers before a page counts as dominantly non-English.

Five rather than one: an English page may quote a foreign phrase, and a
manufacturer with an Indonesian customer may name them. Five distinct function
words is prose, not a mention."""

META_REFRESH = re.compile(
    r"""<meta[^>]+http-equiv\s*=\s*["']?refresh["']?[^>]*content\s*=\s*["'][^"']*url\s*=\s*
        ["']?(?P<url>[^"'\s>]+)""",
    re.IGNORECASE | re.VERBOSE,
)
JS_REDIRECT = re.compile(
    r"""(?:window\.)?location(?:\.href|\.assign|\.replace)?\s*
        (?:=|\(\s*)\s*["'](?P<url>https?://[^"']+)["']""",
    re.IGNORECASE | re.VERBOSE,
)


def registrable_domain(url: str | None) -> str:
    """The registrable part of a URL's host: 'www.a.example.com' -> 'example.com'.

    No public-suffix list, so 'co.uk' groups as 'co.uk'. That over-groups a few
    hosts rather than under-grouping them, which is the safe direction here: it
    can call two related hosts the same domain, never one domain two.
    """
    host = (urlparse(url or "").hostname or "").lower()
    if host.startswith("www."):
        host = host[4:]
    parts = [p for p in host.split(".") if p]
    return ".".join(parts[-2:]) if len(parts) >= 2 else host


def _word_hits(lowered: str, words: tuple[str, ...]) -> list[str]:
    """Whole-word matches only. 'specialist' must never match 'cialis'."""
    found = []
    for word in words:
        pattern = r"\b" + re.escape(word).replace(r"\ ", r"\s+") + r"\b"
        if re.search(pattern, lowered):
            found.append(word)
    return found


def family_hits(text: str) -> dict[str, list[str]]:
    """Every keyword family present in ``text``, with the words that matched."""
    lowered = (text or "").lower()
    return {
        name: hits for name, words in FAMILIES.items()
        if (hits := _word_hits(lowered, words))
    }


def dominant_non_english(text: str) -> list[str]:
    """Markers suggesting the page is not written in English. Empty if it reads English."""
    hits = _word_hits((text or "").lower(), NON_ENGLISH_MARKERS)
    return hits if len(hits) >= NON_ENGLISH_THRESHOLD else []


def looks_parked(text: str) -> list[str]:
    """Parking or for-sale markers. No length ceiling — the Decatur page is 586KB."""
    return _word_hits((text or "").lower(), PARKING)


def redirect_targets(html: str, base_url: str) -> list[str]:
    """Registrable domains this page tries to send a browser to, other than its own."""
    own = registrable_domain(base_url)
    targets = []
    for pattern in (META_REFRESH, JS_REDIRECT):
        for match in pattern.finditer(html or ""):
            target = registrable_domain(match.group("url"))
            if target and target != own and target not in targets:
                targets.append(target)
    return targets


# ------------------------------------------------------------------- coherence

_STOPWORD_TEXT = (
    "a an and are as at be by for from has have in is it its of on or that the "
    "to with will their this these company companies inc llc corp ltd based "
    "services service provides provide including new using use used also"
)
STOPWORDS = frozenset(_STOPWORD_TEXT.split())

INDUSTRY_HINTS = (
    "manufactur", "machin", "mold", "mould", "tool", "die", "fabricat", "weld",
    "plastic", "metal", "steel", "aluminum", "cnc", "injection", "assembly",
    "packaging", "coating", "casting", "extrusion", "stamping", "foundry",
    "automation", "robot", "aerospace", "automotive", "medical", "industrial",
    "engineering", "production", "factory", "plant", "supplier", "components",
    "equipment", "precision", "quality", "iso", "distributor", "wholesale",
    "food", "brewery", "winery", "distiller", "furniture", "cabinet", "wood",
    "textile", "printing", "electronics", "sensor", "laser", "3d printing",
    "additive", "grain", "agricultur", "farm", "seed", "feed", "ethanol",
)
"""Stems, matched at a word start only.

Substring matching here was a real bug: 'die' matched inside 'audience' and
'food' inside other words, so two 586KB togel pages accumulated enough
accidental 'industry vocabulary' to pass coherence and escape quarantine. The
same word-boundary discipline the keyword families use applies here."""
"""Vocabulary a manufacturer's own website tends to use.

Deliberately broad and stem-matched: this is a *floor*, catching pages with no
industrial vocabulary at all, not a classifier that decides which industry."""

MIN_INDUSTRY_HINTS = 2
MIN_DESC_OVERLAP = 2


def industry_tokens(industry_desc: str | None) -> set[str]:
    """Distinctive words from the grant listing's description of the company."""
    words = re.findall(r"[a-z]{4,}", (industry_desc or "").lower())
    return {w for w in words if w not in STOPWORDS}


def coherence(page_text: str, industry_desc: str | None) -> dict[str, Any]:
    """Does this page plausibly describe a business in the stated industry?

    Two signals, both weak on their own and deliberately so:

    * **overlap** — distinctive words shared with the grant listing's own
      description of the company. The listing is T1 and independent of the
      website, so it is the best available statement of what the company does.
    * **industry vocabulary** — whether the page uses any manufacturing words at
      all. A togel site scores zero here however long it is.

    A page is incoherent when it has neither. Requiring both to fail is what
    keeps a thin-but-honest site (a one-page brochure with a photo and a phone
    number) out of the quarantine pile.

    LIMITS. This cannot tell a mold shop from a bakery, and is not trying to: it
    separates "a business page in roughly this world" from "not this company's
    page at all". It will pass a hijack written in industrial English, and it
    will fail an honest site that is entirely images with no text. Both outcomes
    route to a human — nothing is discarded on this signal alone.
    """
    lowered = (page_text or "").lower()
    wanted = industry_tokens(industry_desc)
    overlap = sorted(w for w in wanted if re.search(r"\b" + re.escape(w), lowered))
    hints = sorted({
        h for h in INDUSTRY_HINTS
        if re.search(r"\b" + re.escape(h).replace(r"\ ", r"\s+"), lowered)
    })

    enough_overlap = len(overlap) >= MIN_DESC_OVERLAP
    enough_hints = len(hints) >= MIN_INDUSTRY_HINTS
    return {
        "coherent": bool(enough_overlap or enough_hints),
        "overlap": overlap[:12],
        "industry_hints": hints[:12],
        "had_description": bool(wanted),
    }


def name_in_context(page_text: str, name_tokens: list[str], industry_desc: str | None) -> bool:
    """True when the company name appears inside content that also coheres.

    The old check asked only whether a distinctive token appeared anywhere in the
    DOM. That is satisfiable by a hidden link, a stray comment, or a stolen page
    that happens to mention the town. Requiring the name to sit in text that also
    passes coherence is what makes the check mean "this page is about them".
    """
    if not name_tokens:
        return False
    lowered = (page_text or "").lower()
    if not any(token in lowered for token in name_tokens):
        return False
    return coherence(page_text, industry_desc)["coherent"]


# ------------------------------------------------------------------- the verdict

def assess(
    page_text: str,
    html: str,
    fetched_url: str,
    final_url: str,
    industry_desc: str | None,
) -> dict[str, Any]:
    """Everything the fetch nodes need to decide a website_status.

    Returns the raw findings and a suggested status. The caller records the
    findings whatever it decides, so a later argument about a verdict can be had
    against the evidence rather than against the code.
    """
    families = family_hits(page_text)
    non_english = dominant_non_english(page_text)
    parked = looks_parked(page_text)
    offsite = redirect_targets(html, final_url)
    drifted = registrable_domain(fetched_url) != registrable_domain(final_url)
    coh = coherence(page_text, industry_desc)

    fingerprints: list[str] = []
    for family, words in families.items():
        if family != "parking":
            fingerprints.append(f"{family}: {', '.join(words[:5])}")
    if non_english:
        fingerprints.append(f"dominant non-English content: {', '.join(non_english[:6])}")
    if parked:
        fingerprints.append(f"parking/for-sale template: {', '.join(parked[:3])}")
    if offsite:
        fingerprints.append(f"redirects offsite to: {', '.join(offsite[:3])}")
    if drifted:
        fingerprints.append(
            f"cross-domain redirect {registrable_domain(fetched_url)} -> "
            f"{registrable_domain(final_url)}"
        )

    # 'compromised' means the domain serves somebody else's content, and that
    # claim needs positive evidence of foreign content — a keyword family or
    # prose in an unexpected language. Movement alone is not evidence of theft.
    #
    # An earlier version condemned any page that had drifted domains and failed
    # coherence, and it quarantined two real companies: Lippert Components
    # (lci1.com -> lippert.com) and Fehrenbacher Cabinets (fci3.com ->
    # fehrenbachercabinets.com, where the destination contains the company's own
    # name). Both are ordinary rebrands whose landing pages carry too little
    # extractable text to pass coherence. Failing coherence means "we could not
    # confirm this is theirs", which is a reason to ask a human — not a reason
    # to tell one the site was stolen.
    foreign_content = bool((families.keys() - {"parking"}) or non_english)
    if parked:
        # A parking page is not a hijack; the company's site is simply gone.
        # Both make the content unusable, but calling them the same thing would
        # tell a reader the domain was stolen when it merely lapsed.
        status = "not_found"
    elif foreign_content and not coh["coherent"]:
        status = "compromised"
    else:
        # Drift and offsite redirects are still recorded as fingerprints so a
        # reviewer sees them; they just do not condemn the record on their own.
        status = "ok"

    return {
        "status": status,
        "fingerprints": fingerprints,
        "families": {k: v for k, v in families.items()},
        "non_english": non_english,
        "parked": parked,
        "offsite_redirects": offsite,
        "domain_drift": drifted,
        "coherence": coh,
    }
